
# j@lor
# setting about topologies for kpis project.
---

name: "settlementTopology"
config:
  topology.workers: 1
  topology.debug: true
  topology.message.timeout.secs: 60
  USER: root
  PASSWORD: admin
  DB: storm_config
  HOST: localhost
  PORT: 27017
  name: "settlementTopology"
topologySource:
  className: "org.apache.storm.topologies.FixedKpiTopology"
 # constructorArgs:
 #   - "foo"
 #   - "bar"


